FROM python:3.11-alpine3.20

ENV \
  PYTHONFAULTHANDLER=1 \
  PYTHONUNBUFFERED=1 \
  PYTHONHASHSEED=random \
  PIP_NO_CACHE_DIR=off \
  PIP_DISABLE_PIP_VERSION_CHECK=on \
  PIP_DEFAULT_TIMEOUT=100 \
  POETRY_VERSION=1.3.2

RUN apk update && apk add --no-cache bash libpq curl libxml2 postgresql-dev make poetry nginx git
COPY deploy/nginx.conf /etc/nginx/nginx.conf

RUN pip3 install --upgrade pip

WORKDIR /api
COPY pyproject.toml /api
COPY poetry.lock /api

RUN apk add --no-cache --virtual .build-deps gcc python3-dev musl-dev libffi-dev openssl-dev build-base rust cargo zlib-dev openblas-dev cmake \
  && poetry install --no-root --without dev \
  && apk del --no-cache .build-deps

COPY /src/ /api/src
WORKDIR /api/src

RUN poetry run python manage.py collectstatic --noinput --clear

ENV PORT=8000
EXPOSE 8080
# Runner script here
CMD ["make", "prod"]
